PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX uberon: <http://purl.obolibrary.org/obo/uberon#>
PREFIX cl: <http://purl.obolibrary.org/obo/cl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?meshDescriptor ?label (COUNT(?pmid) AS ?count)
WHERE {

    ?article schema:about ?meshDescriptor ;
             schema:identifier ?pmid .
    ?meshDescriptor rdfs:label ?label .

  FILTER(STRSTARTS(STR(?meshDescriptor), "http://id.nlm.nih.gov/mesh/"))
}
GROUP BY ?meshDescriptor ?label