PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX uberon: <http://purl.obolibrary.org/obo/uberon#>
PREFIX cl: <http://purl.obolibrary.org/obo/cl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?oldConceptID ?meshDescriptor ?descriptorID ?currentConceptID
WHERE {
  # Get SSSOM concepts
  GRAPH <https://purl.humanatlas.io/graph/mesh-uberon-cl-human-mapping> {
    ?axiom a owl:Axiom ;
           owl:annotatedSource ?oldConcept ;
           owl:annotatedProperty skos:exactMatch .
  }
  FILTER(STRSTARTS(STR(?oldConcept), "http://id.nlm.nih.gov/mesh/"))
  BIND(STRAFTER(STR(?oldConcept), "http://id.nlm.nih.gov/mesh/") AS ?oldConceptID)
  
  # Get current MeSH structure
  GRAPH <http://id.nlm.nih.gov/mesh/> {
    ?meshDescriptor a meshv:Descriptor ;
                    meshv:concept ?currentConcept .
  }
  BIND(STRAFTER(STR(?meshDescriptor), "http://id.nlm.nih.gov/mesh/") AS ?descriptorID)
  BIND(STRAFTER(STR(?currentConcept), "http://id.nlm.nih.gov/mesh/") AS ?currentConceptID)
  
  # Only show potential matches
  FILTER(
    ?oldConceptID = ?currentConceptID ||
    CONTAINS(?descriptorID, SUBSTR(?oldConceptID, 2, 5)) ||
    CONTAINS(?oldConceptID, SUBSTR(?descriptorID, 2, 5))
  )
}

## Currently produces no records.