PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX uberon: <http://purl.obolibrary.org/obo/uberon#>
PREFIX cl: <http://purl.obolibrary.org/obo/cl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?pmid
       ?title 
       ?datePublished 
       ?journal_title 
       ?abstract
WHERE {
  ?article a schema:ScholarlyArticle ;
           schema:identifier ?pmid ;
           schema:name ?title ;
           schema:abstract ?abstract ;
           schema:datePublished ?datePublished ;
           schema:isPartOf ?journal ;
           schema:about ?descriptor . 
  ?descriptor ?p mesh:D008099 .
  ?journal a schema:Periodical ;
           schema:name ?journal_title .
}

ORDER BY DESC(?datePublished)
LIMIT 200