PREFIX schema: <http://schema.org/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX MESH: <http://id.nlm.nih.gov/mesh/>
PREFIX HRAlitUniverse: <https://purl.humanatlas.io/graph/hra-lit-universe>

SELECT ?mesh (SAMPLE(?mesh_label) as ?mesh_label) (COUNT(DISTINCT(?pmid)) as ?pmid_count)
FROM MESH:
FROM HRAlitUniverse:
WHERE {
  ?mesh meshv:prefLabel ?mesh_label .
  ?pmid schema:about ?mesh .
}
GROUP BY ?mesh
