PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX uberon: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX cl: <http://purl.obolibrary.org/obo/CL_>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX HRAlit: <https://purl.humanatlas.io/graph/hra-lit>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX MESH_MAPPING: <https://purl.humanatlas.io/graph/mesh-uberon-cl-human-mapping>

# SELECT DISTINCT ?obo ?term
SELECT DISTINCT ?disease ?disease_descriptor ?disease_label
WHERE {
  # Identify set of MeSH descriptors related to Kidney
  GRAPH mesh: {
    mesh:D007674 meshv:treeNumber ?treeNum .
    ?childTreeNum meshv:parentTreeNumber* ?treeNum .
    ?disease_descriptor meshv:treeNumber ?childTreeNum ;
      meshv:preferredConcept ?disease .

    ?disease rdfs:label ?disease_label
  }


  OPTIONAL {
    SERVICE <https://lod.humanatlas.io/sparql> {
      GRAPH <https://purl.humanatlas.io/vocab/hp> {
        ?disease_term oboInOwl:hasDbXref ?xref .
        FILTER(STRSTARTS(?xref, 'MESH:'))
        BIND(IRI(REPLACE(STR(?xref), 'MESH:', STR(mesh:))) as ?disease_descriptor)
      }
    }
  }
  # OPTIONAL {
  #   SERVICE <https://ubergraph.apps.renci.org/sparql> {
  #     GRAPH <http://reasoner.renci.org/ontology> {
  #       ?disease_term oboInOwl:hasDbXref ?xref ;
  #         rdfs:isDefinedBy <http://purl.obolibrary.org/obo/hp.owl>
  #       FILTER(STRSTARTS(?xref, 'MESH:'))
  #       BIND(IRI(REPLACE(STR(?xref), 'MESH:', STR(mesh:))) as ?disease_descriptor)
  #     }
  #   }
  # }
}
ORDER BY ?disease_label
