#+ summary: Named entitie and count of IRI
#+ description: Query provides a table of named entities and the 
#+ count of IRI associated with each entity.

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX uberon: <http://purl.obolibrary.org/obo/uberon#>
PREFIX cl: <http://purl.obolibrary.org/obo/cl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX HRAlit: <https://purl.humanatlas.io/graph/hra-lit>

SELECT ?entityType (COUNT(DISTINCT ?entity) as ?uniqueCount)
WHERE {
  ?entity rdf:type ?entityType .
    # Filter to include only the main entity types from your schema
  
    FILTER(?entityType IN 
           (schema:Periodical,
            schema:PublicationVolume,
            schema:PublicationIssue,
            schema:ScholarlyArticle,
            schema:Organization,
            schema:Person,
            schema:Collection,
            owl:NamedIndividual,
            meshv:TopicalDescriptor,
            meshv:Term,
            meshv:Concept,
            uberon:AnatomicalStructure,
            cl:Cell
  	      	)
          )
     }
     
GROUP BY ?entityType
ORDER BY DESC(?uniqueCount)