PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>

SELECT DISTINCT ?pmid ?descriptor ?label
FROM mesh:

WHERE {
#+ A02 - Musculoskeletal System 
{ mesh:D009141 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ A03 - Digestive System
{ mesh:D004064 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ A04 - Respiratory System 
{ mesh:D012137 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ A05 - Urogenital System
{ mesh:D014566 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ A07 - Cardiovascular System
{ mesh:D002319 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION 
#+ A08 - Nervous System
{ mesh:D009420 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ A15 - Hemic and Immune Systems
{ mesh:D006424 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ Skin
{ mesh:D012867 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ Eyes
{ mesh:D005123 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ Placenta
{ mesh:D010920 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION 
#+ Breasts
{ mesh:D001940 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION
#+ Adipose
{ mesh:D000273 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
} UNION 
#+ Adrenal Gland
{ mesh:D000311 meshv:treeNumber ?treeNum .
  ?childTreeNum meshv:parentTreeNumber* ?treeNum .
  ?descriptor meshv:treeNumber ?childTreeNum .
}

}

ORDER BY ?descriptor