#+ summary: Named graphs in the db
#+ description: All named graphs in the queried SPARQL database

SELECT ?graph (COUNT(*) as ?triples) WHERE {
  GRAPH ?graph {
    ?s ?p ?o .
  }
}
GROUP BY ?graph
ORDER BY ?graph

SELECT ?namedGraph (COUNT(DISTINCT ?entity) as ?totalEntities) (COUNT(DISTINCT ?entityType) as ?uniqueTypes)
WHERE {
  GRAPH ?namedGraph {
    ?entity rdf:type ?entityType .
  }
}
GROUP BY ?namedGraph
ORDER BY DESC(?totalEntities)